const employees = [{
    full_name: 'Ching Gathers',
    salary: 2000,
    address: '8491 Manchester Lane Riverdale, GA 30274',
    manager: 1,
    department_no: 1,
  },
  {
    full_name: 'Kathrine Noell',
    salary: 2200,
    address: '8538 Lantern St. New Kensington, PA 15068',
    manager: 1,
    department_no: 2,
  },
  {
    full_name: 'Jenise Graver',
    salary: 3300,
    address: '7362 Bayport Drive Marquette, MI 49855',
    manager: 1,
    department_no: 3,
  },
  {
    full_name: 'Elana Padgett',
    salary: 2300,
    address: '325 Elm Rd. Hackensack, NJ 07601',
    manager: 3,
    department_no: 4,
  },
  {
    full_name: 'Scot Ihle',
    salary: 2400,
    address: '5 West Glenwood Ave. Portsmouth, VA 23703',
    manager: 3,
    department_no: 5,
  },
  {
    full_name: 'Peggie Coffey',
    salary: 3400,
    address: '761 Homestead Road Vincentown, NJ 08088',
    manager: 3,
    department_no: 6,
  },
  {
    full_name: 'Nona Mcvey',
    salary: 2500,
    address: '110 Tailwater Circle Douglasville, GA 30134',
    manager: 3,
    department_no: 7,
  },
  {
    full_name: 'Britney Gehrke',
    salary: 2700,
    address: '8182 Mill Pond St. Peachtree City, GA 30269',
    manager: 3,
    department_no: 8,
  },
  {
    full_name: 'Jaqueline Eddie',
    salary: 2200,
    address: '169 Walt Whitman Lane Niagara Falls, NY 14304',
    manager: 2,
    department_no: 9,
  },
  {
    full_name: 'Rey Bevil',
    salary: 3000,
    address: '8920 Beaver Ridge St. Athens, GA 30605',
    manager: 2,
    department_no: 10,
  },
  {
    full_name: 'Mitsue Barks',
    salary: 2300,
    address: '9231 S. Jackson Drive Winchester, VA 22601',
    manager: 2,
    department_no: 9,
  },
  {
    full_name: 'Miquel Groesbeck',
    salary: 2500,
    address: '8244 N. Stillwater Court Upper Darby, PA 19082',
    manager: 2,
    department_no: 10,
  },
  {
    full_name: 'Rivka Olive',
    salary: 2800,
    address: '8039 Second Drive Tullahoma, TN 37388',
    manager: 4,
    department_no: 8,
  },
  {
    full_name: 'Jacquiline Kirkbride',
    salary: 2600,
    address: '8403 Parker Street Canonsburg, PA 15317',
    manager: 4,
    department_no: 7,
  },
  {
    full_name: 'Alayna Briceno',
    salary: 4000,
    address: '8330 Old Liberty St. Howard Beach, NY 11414',
    manager: 4,
    department_no: 6,
  },
  {
    full_name: 'Keila Chase',
    salary: 2300,
    address: '38 Sierra Rd. Daphne, AL 36526',
    manager: 5,
    department_no: 5,
  },
  {
    full_name: 'Deanna Capito',
    salary: 2300,
    address: '9 Devon St. Omaha, NE 68107',
    manager: 5,
    department_no: 4,
  },
  {
    full_name: 'Lionel Bryner',
    salary: 2100,
    address: '7573 High Noon Avenue North Ridgeville, OH 44039',
    manager: 5,
    department_no: 3,
  },
  {
    full_name: 'Fawn Pippen',
    salary: 1900,
    address: '8837 North Ocean St. Long Beach, NY 11561',
    manager: 5,
    department_no: 2,
  },
  {
    full_name: 'Joi Hotchkiss',
    salary: 2900,
    address: '9315 Lafayette Street Waterloo, IA 50701',
    manager: 5,
    department_no: 1,
  },
  ];
  
  const departments = [{
    dept_no: 1,
    title: 'Agency of Mainframe Acquisition and Application Programming',
    description: 'Try Virtel starter edition, free! mainframe web compliant. Thin-client 3270 access. Services: mainframe modernization, secure 3270 web access, thin-client web browsers.',
    address: '887 Lynn Street Brookline',
  },
  {
    dept_no: 2,
    title: 'Agency of Mainframe Internet Technology and Network Development',
    description: 'The Advanced Research Projects Agency Network (ARPANET) was an early packet-switching network and the first network to implement the TCP/IP protocol suite. Both technologies became the technical foundation of the Internet.',
    address: '887 Lynn Street Brookline',
  },
  {
    dept_no: 3,
    title: 'Agency of Portable Source Code Backup',
    description: 'UrBackup is an easy to setup Open Source client/server backup system, that through a combination of image and file backups accomplishes both data safety',
    address: '887 Lynn Street Brookline',
  },
  {
    dept_no: 4,
    title: 'Agency of Telecommunications Multimedia Acquisition and Wireless Source Code Troubleshooting',
    description: ' Agency of Mainframe Acquisition and Intranet Maintenance. 3 ... Branch of Intranet Networking and Source Code Development ... Division of Wireless Internet Programming ... Open-Source Multimedia Programming and Technology Division ... Telecommunications Backup and Implementation Department',
    address: '887 Lynn Street Brookline',
  },
  {
    dept_no: 5,
    title: 'Analytical Database Security Branch',
    description: 'Analytic database is an important branch of database product which was built to store, manage and consume massive data. It is designed to be used specifically ...',
    address: '2797  Leverton Cove Road Palmer',
  },
  {
    dept_no: 6,
    title: 'Bureau of Internet Administration',
    description: 'The Advanced Research Projects Agency Network (ARPANET) was an early packet-switching network and the first network to implement the TCP/IP protocol suite. Both technologies became the technical foundation of the Internet. ... Taylor had three computer terminals in his office, each connected to separate computers',
    address: '2797  Leverton Cove Road Palmer',
  },
  {
    dept_no: 7,
    title: 'Bureau of Internet Intranet Implementation',
    description: 'What advantages will implementing an intranet bring to my company? What are the ... What is the difference between intranet vs. extranet vs. internet? What facilitates a ... Think of a school, university, an office and more.',
    address: '2797  Leverton Cove Road Palmer',
  },
  {
    dept_no: 8,
    title: 'Data Troubleshooting and Security Committee',
    description: 'Data protection professionals and organization management officers share a ... in privacy and security, with innovative cross-education and stellar networking. ... of a DPO but rather whether a data protection committee exists that would ... However, this does not solve the problem of operational compliance.',
    address: '2797  Leverton Cove Road Palmer',
  },
  {
    dept_no: 9,
    title: 'Department of Extranet Intranet Connectivity',
    description: 'Extranets—Saving Money on Customer Service. Extranets use a web interface for secure access by customers, business partners, and temporary employees. Organizations typically limit access to applications more so than intranets because they are used with outside individuals and organizations.',
    address: '2797  Leverton Cove Road Palmer',
  },
  {
    dept_no: 10,
    title: 'Department of Telecommunications Programming Technology',
    description: ' Financial assistance for the furtherance of research and study in telecommunications technology and for building up adequately trained ...',
    address: '2797  Leverton Cove Road Palmer',
  },
  ];
  
  module.exports = {
    employees,
    departments
  }; 